services:
  vps-win:
    build: .
    container_name: vps-win-free-tool
    devices:
      - /dev/kvm:/dev/kvm
    ports:
      - "6080:6080"
      - "3389:3389"
    volumes:
      - windows_data:/data
      - windows_iso:/iso
    restart: unless-stopped

volumes:
  windows_data:
  windows_iso:
